version: '3.5'
services:
  na-tg-admin:
    image: ghcr.io/news-aggregator-bot/bepicky.na-tg-admin
    environment:
      - TG_ADMIN_TOKEN=${TG_ADMIN_TOKEN}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - 8075:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300M"
        reservations:
          cpus: "0.1"
          memory: "128M"
networks:
  default:
    external:
      name: picky

