server:
  port: 8080
camel:
  main:
    banner-mode: "off"
  springboot:
    main-run-controller: true
bot:
  telegram:
    name: bepicky-admin
    token: ${TG_ADMIN_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.security: INFO
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  application:
    name: na-tg-admin
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
  config:
    import: "optional:configserver:"
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
topics:
  user:
    register: user.register
  message:
    text: msg.txt
